### ISSUE TITLE
Test that pkg can be installed via devtools

### ISSUE THREAD

**Issue by quantifish** [quantifish/TagGrowth#16]

**Comment by quantifish** [comment]
Can you install the package using devtools Jim? i.e. install_github("quantifish/TagGrowth")

**Comment by James-Thorson** [comment]
yup, loaded fine.  If there's a single example function I can try running,
happy to.  otherwise, buried with assessment until sometime next month.

thanks for checking!

jim

**Comment by quantifish** [comment]
Cheers Jim, it worked for me in the end too, just takes a long time to download. I'll tidy up the code for running stuff and get back to you about running a few things. No rush for now.

Darcy
