### ISSUE TITLE
I found a mistake with sd_z

### ISSUE THREAD

**Issue by quantifish** [quantifish/TagGrowth#17]
I found a bit of a problem. I've simulated from 2 x sd_z parameters (females and males), but the model only fits 1 x sd_z parameter (as we discussed previously). I'll fix this up so that we're simulating from 1 x sd_z parameter as well.

**Comment by quantifish** [comment]
Fixed and done

**Comment by James-Thorson** [comment]
OK, I just started editing should I let you commit and restart in an hour?

**Comment by quantifish** [comment]
Ooops, I'll commit right now and you can start editing in 5 mins if 
that's ok. I'll spend a few hours on stuff today, but I'll be working on 
the case study fits and figures (having a little issue with annual 
deviations models).

Cheers Jim
D


On 24/01/15 12:03, Jim Thorson wrote:
> OK, I just started editing should I let you commit and restart in an 
> hour?
>
> On Fri, Jan 23, 2015 at 2:59 PM, Darcy Webber <notifications@github.com>
> wrote:
>
> > Closed #17 <https://github.com/quantifish/TagGrowth/issues/17>.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/quantifish/TagGrowth/issues/17#event-224031675>.
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/quantifish/TagGrowth/issues/17#issuecomment-71281739>.
>

-- 
--------------------------------------------------
Darcy Webber
Quantifish | Quantitative Marine Science Solutions
P: 021 0233 0163
E: darcy@quantifish.co.nz
W: www.quantifish.co.nz
--------------------------------------------------

Visit the ADMB project http://admb-project.org/

**Comment by James-Thorson** [comment]
OK, I renamed the DOC X_JT.docx, and could you just merge the two when you
get a chance?  sorry, should have emailed before starting to work on it!

cheers,
jim

**Comment by quantifish** [comment]
No worries Jim, all good.

On 24/01/15 12:18, Jim Thorson wrote:
> OK, I renamed the DOC X_JT.docx, and could you just merge the two when 
> you
> get a chance? sorry, should have emailed before starting to work on it!
>
> cheers,
> jim
>
> On Fri, Jan 23, 2015 at 3:09 PM, Darcy Webber <notifications@github.com>
> wrote:
>
> > Ooops, I'll commit right now and you can start editing in 5 mins if
> > that's ok. I'll spend a few hours on stuff today, but I'll be 
> working on
> > the case study fits and figures (having a little issue with annual
> > deviations models).
> >
> > Cheers Jim
> > D
> >
> >
> > On 24/01/15 12:03, Jim Thorson wrote:
> > > OK, I just started editing should I let you commit and restart in an
> > > hour?
> > >
> > > On Fri, Jan 23, 2015 at 2:59 PM, Darcy Webber 
> <notifications@github.com>
> > > wrote:
> > >
> > > > Closed #17 <https://github.com/quantifish/TagGrowth/issues/17>.
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/quantifish/TagGrowth/issues/17#event-224031675>.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > 
> <https://github.com/quantifish/TagGrowth/issues/17#issuecomment-71281739
> > >.
> > >
> >
> > --
> > --------------------------------------------------
> > Darcy Webber
> > Quantifish | Quantitative Marine Science Solutions
> > P: 021 0233 0163
> > E: darcy@quantifish.co.nz
> > W: www.quantifish.co.nz
> > --------------------------------------------------
> >
> > Visit the ADMB project http://admb-project.org/
> >
> > —
> > Reply to this email directly or view it on GitHub
> > 
> <https://github.com/quantifish/TagGrowth/issues/17#issuecomment-71282385>.
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/quantifish/TagGrowth/issues/17#issuecomment-71283360>.
>

-- 
--------------------------------------------------
Darcy Webber
Quantifish | Quantitative Marine Science Solutions
P: 021 0233 0163
E: darcy@quantifish.co.nz
W: www.quantifish.co.nz
--------------------------------------------------

Visit the ADMB project http://admb-project.org/

**Comment by James-Thorson** [comment]
Darcy,

I agree that the methods are getting close.

Are you willing to write the results by yourself?  If yes, please lead the
results with the most important result, and only then put summary of
diagnostics etc.  Also, as written now, the methods has case study first
and simulation experiment second, so please use that order for the results.
 we can then play around with ordering later.

I'll plan to keep working on the discussion for a few minutes and will
upload what I have in prob. 30 min.

cheers,
jim

**Comment by quantifish** [comment]
Yep, I'm happy to get stuck into the results. I'll do so today once 
you've uploaded to avoid issues.

Cheers
Darcy

On 24/01/15 12:38, Jim Thorson wrote:
> Darcy,
>
> I agree that the methods are getting close.
>
> Are you willing to write the results by yourself? If yes, please lead the
> results with the most important result, and only then put summary of
> diagnostics etc. Also, as written now, the methods has case study first
> and simulation experiment second, so please use that order for the 
> results.
> we can then play around with ordering later.
>
> I'll plan to keep working on the discussion for a few minutes and will
> upload what I have in prob. 30 min.
>
> cheers,
> jim
>
>
>
> On Fri, Jan 23, 2015 at 3:28 PM, Darcy Webber <notifications@github.com>
> wrote:
>
> > No worries Jim, all good.
> >
> > On 24/01/15 12:18, Jim Thorson wrote:
> > > OK, I renamed the DOC X_JT.docx, and could you just merge the two 
> when
> > > you
> > > get a chance? sorry, should have emailed before starting to work 
> on it!
> > >
> > > cheers,
> > > jim
> > >
> > > On Fri, Jan 23, 2015 at 3:09 PM, Darcy Webber 
> <notifications@github.com>
> > > wrote:
> > >
> > > > Ooops, I'll commit right now and you can start editing in 5 mins if
> > > > that's ok. I'll spend a few hours on stuff today, but I'll be
> > > working on
> > > > the case study fits and figures (having a little issue with annual
> > > > deviations models).
> > > >
> > > > Cheers Jim
> > > > D
> > > >
> > > >
> > > > On 24/01/15 12:03, Jim Thorson wrote:
> > > > > OK, I just started editing should I let you commit and restart 
> in an
> > > > > hour?
> > > > >
> > > > > On Fri, Jan 23, 2015 at 2:59 PM, Darcy Webber
> > > <notifications@github.com>
> > > > > wrote:
> > > > >
> > > > > > Closed #17 <https://github.com/quantifish/TagGrowth/issues/17>.
> > > > > >
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub
> > > > > > 
> <https://github.com/quantifish/TagGrowth/issues/17#event-224031675
> > >.
> > > > > >
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > >
> > > 
> <https://github.com/quantifish/TagGrowth/issues/17#issuecomment-71281739
> > > > >.
> > > > >
> > > >
> > > > --
> > > > --------------------------------------------------
> > > > Darcy Webber
> > > > Quantifish | Quantitative Marine Science Solutions
> > > > P: 021 0233 0163
> > > > E: darcy@quantifish.co.nz
> > > > W: www.quantifish.co.nz
> > > > --------------------------------------------------
> > > >
> > > > Visit the ADMB project http://admb-project.org/
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > >
> > > 
> <https://github.com/quantifish/TagGrowth/issues/17#issuecomment-71282385
> > >.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > 
> <https://github.com/quantifish/TagGrowth/issues/17#issuecomment-71283360
> > >.
> > >
> >
> > --
> > --------------------------------------------------
> > Darcy Webber
> > Quantifish | Quantitative Marine Science Solutions
> > P: 021 0233 0163
> > E: darcy@quantifish.co.nz
> > W: www.quantifish.co.nz
> > --------------------------------------------------
> >
> > Visit the ADMB project http://admb-project.org/
> >
> > —
> > Reply to this email directly or view it on GitHub
> > 
> <https://github.com/quantifish/TagGrowth/issues/17#issuecomment-71284474>.
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/quantifish/TagGrowth/issues/17#issuecomment-71285595>.
>

-- 
--------------------------------------------------
Darcy Webber
Quantifish | Quantitative Marine Science Solutions
P: 021 0233 0163
E: darcy@quantifish.co.nz
W: www.quantifish.co.nz
--------------------------------------------------

Visit the ADMB project http://admb-project.org/

**Comment by James-Thorson** [comment]
Darcy,

just uploaded some discusison text.  please tell me when the results are in
rough-draft form and I'll keep working.

and thanks for making good progress!

jim

**Comment by quantifish** [comment]
Cool, I'll get on it now. No worries, thank you too mate. Hopefully we 
can knock this on the head soon.

Darcy


On 24/01/15 13:04, Jim Thorson wrote:
> Darcy,
>
> just uploaded some discusison text. please tell me when the results 
> are in
> rough-draft form and I'll keep working.
>
> and thanks for making good progress!
>
> jim
>
> On Fri, Jan 23, 2015 at 3:42 PM, Darcy Webber <notifications@github.com>
> wrote:
>
> > Yep, I'm happy to get stuck into the results. I'll do so today once
> > you've uploaded to avoid issues.
> >
> > Cheers
> > Darcy
> >
> >
> > On 24/01/15 12:38, Jim Thorson wrote:
> > > Darcy,
> > >
> > > I agree that the methods are getting close.
> > >
> > > Are you willing to write the results by yourself? If yes, please 
> lead the
> > > results with the most important result, and only then put summary of
> > > diagnostics etc. Also, as written now, the methods has case study 
> first
> > > and simulation experiment second, so please use that order for the
> > > results.
> > > we can then play around with ordering later.
> > >
> > > I'll plan to keep working on the discussion for a few minutes and 
> will
> > > upload what I have in prob. 30 min.
> > >
> > > cheers,
> > > jim
> > >
> > >
> > >
> > > On Fri, Jan 23, 2015 at 3:28 PM, Darcy Webber 
> <notifications@github.com>
> > > wrote:
> > >
> > > > No worries Jim, all good.
> > > >
> > > > On 24/01/15 12:18, Jim Thorson wrote:
> > > > > OK, I renamed the DOC X_JT.docx, and could you just merge the two
> > > when
> > > > > you
> > > > > get a chance? sorry, should have emailed before starting to work
> > > on it!
> > > > >
> > > > > cheers,
> > > > > jim
> > > > >
> > > > > On Fri, Jan 23, 2015 at 3:09 PM, Darcy Webber
> > > <notifications@github.com>
> > > > > wrote:
> > > > >
> > > > > > Ooops, I'll commit right now and you can start editing in 5 
> mins if
> > > > > > that's ok. I'll spend a few hours on stuff today, but I'll be
> > > > > working on
> > > > > > the case study fits and figures (having a little issue with 
> annual
> > > > > > deviations models).
> > > > > >
> > > > > > Cheers Jim
> > > > > > D
> > > > > >
> > > > > >
> > > > > > On 24/01/15 12:03, Jim Thorson wrote:
> > > > > > > OK, I just started editing should I let you commit and 
> restart
> > > in an
> > > > > > > hour?
> > > > > > >
> > > > > > > On Fri, Jan 23, 2015 at 2:59 PM, Darcy Webber
> > > > > <notifications@github.com>
> > > > > > > wrote:
> > > > > > >
> > > > > > > > Closed #17 
> <https://github.com/quantifish/TagGrowth/issues/17
> > >.
> > > > > > > >
> > > > > > > > —
> > > > > > > > Reply to this email directly or view it on GitHub
> > > > > > > >
> > > <https://github.com/quantifish/TagGrowth/issues/17#event-224031675
> > > > >.
> > > > > > > >
> > > > > > >
> > > > > > > —
> > > > > > > Reply to this email directly or view it on GitHub
> > > > > > >
> > > > >
> > > 
> <https://github.com/quantifish/TagGrowth/issues/17#issuecomment-71281739
> > > > > > >.
> > > > > > >
> > > > > >
> > > > > > --
> > > > > > --------------------------------------------------
> > > > > > Darcy Webber
> > > > > > Quantifish | Quantitative Marine Science Solutions
> > > > > > P: 021 0233 0163
> > > > > > E: darcy@quantifish.co.nz
> > > > > > W: www.quantifish.co.nz
> > > > > > --------------------------------------------------
> > > > > >
> > > > > > Visit the ADMB project http://admb-project.org/
> > > > > >
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub
> > > > > >
> > > > >
> > > 
> <https://github.com/quantifish/TagGrowth/issues/17#issuecomment-71282385
> > > > >.
> > > > > >
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > >
> > > 
> <https://github.com/quantifish/TagGrowth/issues/17#issuecomment-71283360
> > > > >.
> > > > >
> > > >
> > > > --
> > > > --------------------------------------------------
> > > > Darcy Webber
> > > > Quantifish | Quantitative Marine Science Solutions
> > > > P: 021 0233 0163
> > > > E: darcy@quantifish.co.nz
> > > > W: www.quantifish.co.nz
> > > > --------------------------------------------------
> > > >
> > > > Visit the ADMB project http://admb-project.org/
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > >
> > > 
> <https://github.com/quantifish/TagGrowth/issues/17#issuecomment-71284474
> > >.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > 
> <https://github.com/quantifish/TagGrowth/issues/17#issuecomment-71285595
> > >.
> > >
> >
> > --
> > --------------------------------------------------
> > Darcy Webber
> > Quantifish | Quantitative Marine Science Solutions
> > P: 021 0233 0163
> > E: darcy@quantifish.co.nz
> > W: www.quantifish.co.nz
> > --------------------------------------------------
> >
> > Visit the ADMB project http://admb-project.org/
> >
> > —
> > Reply to this email directly or view it on GitHub
> > 
> <https://github.com/quantifish/TagGrowth/issues/17#issuecomment-71285990>.
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/quantifish/TagGrowth/issues/17#issuecomment-71287953>.
>

-- 
--------------------------------------------------
Darcy Webber
Quantifish | Quantitative Marine Science Solutions
P: 021 0233 0163
E: darcy@quantifish.co.nz
W: www.quantifish.co.nz
--------------------------------------------------

Visit the ADMB project http://admb-project.org/

**Comment by James-Thorson** [comment]
Darcy,

I just checked -- were you going to merge the TagGrowth.doc and
TagGrowth_JTT.doc?  The commit history includes the word 'merge' but
TagGrowth.doc doesn't contain the text I added this afternoon.

sorry again about the version mix-up.  I might have time tomorrow to do
some quick writing, is the only reason I ask on a friday ;)

jim

**Comment by quantifish** [comment]
Hi Jim

Done, no worries about the mix up, I'd not changed a whole lot anyway, 
so use the TagGrowth.doc version.

Cheers
Darcy

On 24/01/15 16:35, Jim Thorson wrote:
> Darcy,
>
> I just checked -- were you going to merge the TagGrowth.doc and
> TagGrowth_JTT.doc? The commit history includes the word 'merge' but
> TagGrowth.doc doesn't contain the text I added this afternoon.
>
> sorry again about the version mix-up. I might have time tomorrow to do
> some quick writing, is the only reason I ask on a friday ;)
>
> jim
>
> On Fri, Jan 23, 2015 at 4:08 PM, Darcy Webber <notifications@github.com>
> wrote:
>
> > Cool, I'll get on it now. No worries, thank you too mate. Hopefully we
> > can knock this on the head soon.
> >
> > Darcy
> >
> >
> >
> > On 24/01/15 13:04, Jim Thorson wrote:
> > > Darcy,
> > >
> > > just uploaded some discusison text. please tell me when the results
> > > are in
> > > rough-draft form and I'll keep working.
> > >
> > > and thanks for making good progress!
> > >
> > > jim
> > >
> > > On Fri, Jan 23, 2015 at 3:42 PM, Darcy Webber 
> <notifications@github.com>
> > > wrote:
> > >
> > > > Yep, I'm happy to get stuck into the results. I'll do so today once
> > > > you've uploaded to avoid issues.
> > > >
> > > > Cheers
> > > > Darcy
> > > >
> > > >
> > > > On 24/01/15 12:38, Jim Thorson wrote:
> > > > > Darcy,
> > > > >
> > > > > I agree that the methods are getting close.
> > > > >
> > > > > Are you willing to write the results by yourself? If yes, please
> > > lead the
> > > > > results with the most important result, and only then put 
> summary of
> > > > > diagnostics etc. Also, as written now, the methods has case study
> > > first
> > > > > and simulation experiment second, so please use that order for 
> the
> > > > > results.
> > > > > we can then play around with ordering later.
> > > > >
> > > > > I'll plan to keep working on the discussion for a few minutes and
> > > will
> > > > > upload what I have in prob. 30 min.
> > > > >
> > > > > cheers,
> > > > > jim
> > > > >
> > > > >
> > > > >
> > > > > On Fri, Jan 23, 2015 at 3:28 PM, Darcy Webber
> > > <notifications@github.com>
> > > > > wrote:
> > > > >
> > > > > > No worries Jim, all good.
> > > > > >
> > > > > > On 24/01/15 12:18, Jim Thorson wrote:
> > > > > > > OK, I renamed the DOC X_JT.docx, and could you just merge 
> the two
> > > > > when
> > > > > > > you
> > > > > > > get a chance? sorry, should have emailed before starting 
> to work
> > > > > on it!
> > > > > > >
> > > > > > > cheers,
> > > > > > > jim
> > > > > > >
> > > > > > > On Fri, Jan 23, 2015 at 3:09 PM, Darcy Webber
> > > > > <notifications@github.com>
> > > > > > > wrote:
> > > > > > >
> > > > > > > > Ooops, I'll commit right now and you can start editing in 5
> > > mins if
> > > > > > > > that's ok. I'll spend a few hours on stuff today, but 
> I'll be
> > > > > > > working on
> > > > > > > > the case study fits and figures (having a little issue with
> > > annual
> > > > > > > > deviations models).
> > > > > > > >
> > > > > > > > Cheers Jim
> > > > > > > > D
> > > > > > > >
> > > > > > > >
> > > > > > > > On 24/01/15 12:03, Jim Thorson wrote:
> > > > > > > > > OK, I just started editing should I let you commit and
> > > restart
> > > > > in an
> > > > > > > > > hour?
> > > > > > > > >
> > > > > > > > > On Fri, Jan 23, 2015 at 2:59 PM, Darcy Webber
> > > > > > > <notifications@github.com>
> > > > > > > > > wrote:
> > > > > > > > >
> > > > > > > > > > Closed #17
> > > <https://github.com/quantifish/TagGrowth/issues/17
> > > > >.
> > > > > > > > > >
> > > > > > > > > > —
> > > > > > > > > > Reply to this email directly or view it on GitHub
> > > > > > > > > >
> > > > > 
> <https://github.com/quantifish/TagGrowth/issues/17#event-224031675
> > > > > > >.
> > > > > > > > > >
> > > > > > > > >
> > > > > > > > > —
> > > > > > > > > Reply to this email directly or view it on GitHub
> > > > > > > > >
> > > > > > >
> > > > >
> > > 
> <https://github.com/quantifish/TagGrowth/issues/17#issuecomment-71281739
> > > > > > > > >.
> > > > > > > > >
> > > > > > > >
> > > > > > > > --
> > > > > > > > --------------------------------------------------
> > > > > > > > Darcy Webber
> > > > > > > > Quantifish | Quantitative Marine Science Solutions
> > > > > > > > P: 021 0233 0163
> > > > > > > > E: darcy@quantifish.co.nz
> > > > > > > > W: www.quantifish.co.nz
> > > > > > > > --------------------------------------------------
> > > > > > > >
> > > > > > > > Visit the ADMB project http://admb-project.org/
> > > > > > > >
> > > > > > > > —
> > > > > > > > Reply to this email directly or view it on GitHub
> > > > > > > >
> > > > > > >
> > > > >
> > > 
> <https://github.com/quantifish/TagGrowth/issues/17#issuecomment-71282385
> > > > > > >.
> > > > > > > >
> > > > > > >
> > > > > > > —
> > > > > > > Reply to this email directly or view it on GitHub
> > > > > > >
> > > > >
> > > 
> <https://github.com/quantifish/TagGrowth/issues/17#issuecomment-71283360
> > > > > > >.
> > > > > > >
> > > > > >
> > > > > > --
> > > > > > --------------------------------------------------
> > > > > > Darcy Webber
> > > > > > Quantifish | Quantitative Marine Science Solutions
> > > > > > P: 021 0233 0163
> > > > > > E: darcy@quantifish.co.nz
> > > > > > W: www.quantifish.co.nz
> > > > > > --------------------------------------------------
> > > > > >
> > > > > > Visit the ADMB project http://admb-project.org/
> > > > > >
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub
> > > > > >
> > > > >
> > > 
> <https://github.com/quantifish/TagGrowth/issues/17#issuecomment-71284474
> > > > >.
> > > > > >
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > >
> > > 
> <https://github.com/quantifish/TagGrowth/issues/17#issuecomment-71285595
> > > > >.
> > > > >
> > > >
> > > > --
> > > > --------------------------------------------------
> > > > Darcy Webber
> > > > Quantifish | Quantitative Marine Science Solutions
> > > > P: 021 0233 0163
> > > > E: darcy@quantifish.co.nz
> > > > W: www.quantifish.co.nz
> > > > --------------------------------------------------
> > > >
> > > > Visit the ADMB project http://admb-project.org/
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > >
> > > 
> <https://github.com/quantifish/TagGrowth/issues/17#issuecomment-71285990
> > >.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > 
> <https://github.com/quantifish/TagGrowth/issues/17#issuecomment-71287953
> > >.
> > >
> >
> > --
> > --------------------------------------------------
> > Darcy Webber
> > Quantifish | Quantitative Marine Science Solutions
> > P: 021 0233 0163
> > E: darcy@quantifish.co.nz
> > W: www.quantifish.co.nz
> > --------------------------------------------------
> >
> > Visit the ADMB project http://admb-project.org/
> >
> > —
> > Reply to this email directly or view it on GitHub
> > 
> <https://github.com/quantifish/TagGrowth/issues/17#issuecomment-71288260>.
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/quantifish/TagGrowth/issues/17#issuecomment-71298555>.
>

-- 
--------------------------------------------------
Darcy Webber
Quantifish | Quantitative Marine Science Solutions
P: 021 0233 0163
E: darcy@quantifish.co.nz
W: www.quantifish.co.nz
--------------------------------------------------

Visit the ADMB project http://admb-project.org/
