### ISSUE TITLE
Random-effects for k and z model...

### ISSUE THREAD

**Issue by quantifish** [quantifish/TagGrowth#21]
...while writing up I noticed that the sd_k,s for females was being estimated as 0.001. This is the lower bound that we are imposing during estimation. I changed the lower bound to be 0.0001 and this is what the model estimated that value to be again.

It seems that all the variability is being lumped into z and the c.v. Does this sound like a resonable outcome?

**Comment by James-Thorson** [comment]
What about sd_k for males?

I trust our sim results so yes, seems reasonable

**Comment by quantifish** [comment]
For males it's sitting off the bound at sd_k = 0.00143.


On 02/02/15 08:48, Jim Thorson wrote:
> What about sd_k for males?
>
> I trust our sim results so yes, seems reasonable
>
> Sent from my iPhone
>
> > On Feb 1, 2015, at 11:10 AM, Darcy Webber <notifications@github.com> 
> wrote:
> >
> > ...while writing up I noticed that the sd_k,s for females was being 
> estimated as 0.001. This is the lower bound that we are imposing 
> during estimation. I changed the lower bound to be 0.0001 and this is 
> what the model estimated that value to be again.
> >
> > It seems that all the variability is being lumped into z and the 
> c.v. Does this sound like a resonable outcome?
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/quantifish/TagGrowth/issues/21#issuecomment-72380573>.
>

-- 
--------------------------------------------------
Darcy Webber
Quantifish | Quantitative Marine Science Solutions
P: 021 0233 0163
E: darcy@quantifish.co.nz
W: www.quantifish.co.nz
--------------------------------------------------

Visit the ADMB project http://admb-project.org/

**Comment by quantifish** [comment]
P.S. I'm working through the write up at the mo, I should be done by 
lunchtime (in a couple of hours).


On 02/02/15 08:48, Jim Thorson wrote:
> What about sd_k for males?
>
> I trust our sim results so yes, seems reasonable
>
> Sent from my iPhone
>
> > On Feb 1, 2015, at 11:10 AM, Darcy Webber <notifications@github.com> 
> wrote:
> >
> > ...while writing up I noticed that the sd_k,s for females was being 
> estimated as 0.001. This is the lower bound that we are imposing 
> during estimation. I changed the lower bound to be 0.0001 and this is 
> what the model estimated that value to be again.
> >
> > It seems that all the variability is being lumped into z and the 
> c.v. Does this sound like a resonable outcome?
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/quantifish/TagGrowth/issues/21#issuecomment-72380573>.
>

-- 
--------------------------------------------------
Darcy Webber
Quantifish | Quantitative Marine Science Solutions
P: 021 0233 0163
E: darcy@quantifish.co.nz
W: www.quantifish.co.nz
--------------------------------------------------

Visit the ADMB project http://admb-project.org/

**Comment by James-Thorson** [comment]
So our model is predicting that all first obs that are below average length have a 50% chance of being above average on resighting. You could check this if you doubt our model results

**Comment by James-Thorson** [comment]
Actually nm, that's only true when time at liberty is large relative to Age1
