### ISSUE TITLE
Reviewer #3

### ISSUE THREAD

**Issue by quantifish** [quantifish/TagGrowth#28]
- [x] 153: Conventional ageing methods. Do you assume ageing is done without error? Is that reasonable for this species?
- [x] 166: Did you try any  sensitivities with some other value of psi? Was this parameter important?
- [x] 174: "Standard errors are then estimated via the information matrix and delta-method." Some more detail on this would be useful. 
- [x] 190: Delete extra "in the"
- [x] 208: Where these parameters the same for males and females? 
- [x] 209-210: You already said that psi was fixed at zero for the case study. 
- [x] 265-267: Estimate of L0. Judging from figure 1, there were very few data points for fish younger than 3. Was this true for the data-set used in Dunn as well? Differences between the results in this study and Dunn et al. are probably caused by differences in sample size of small fish rather than any difference in methodology.

**Comment by quantifish** [comment]
Hey Jim,

RE the comment above "Standard errors are then estimated via the information matrix and delta-method." Some more detail on this would be useful".  You know of any refs for this or have a quick explanation written up elsewhere?

OK so the first part of the simulation/estimation bit is done now. Another 5 days or so for the final set, that is the simulated k and z for 50, 100, 250 and 500 with all models applied (4 x 4 x 200).

**Comment by James-Thorson** [comment]
happy to chip in text for this and other spots.  once you've updated the
figures with the new simulation experiment (i.e., for the different
simulators given a fixed sample size) and for the previous power analysis,
please tell me and I'll dive into the text a bit.

cheers,
jim

**Comment by quantifish** [comment]
Cheers Jim, I'll let you know when the simulations finish and I have the plots done. It is going to be cutting it close for the 4 week turnaround...

**Comment by James-Thorson** [comment]
We can also ask for a small extension, no one ever says no to a 2-4 week request
