### ISSUE TITLE
Reviewer #2

### ISSUE THREAD

**Issue by quantifish** [quantifish/TagGrowth#29]
Major comments
- [x] 1. The introduction is generally difficult to read. To help the reader, I suggest you introduce the general concept of persistent and transient growth e.g. in line 56 before describing these aspects in details.
- [x] The sentences in lines 53-55 ("Similarly …") and lines 60-63 ('For example…") do not link with the previous sentences. 
- [x] Also, you have to more specific with 'size-specific harvest' (line 61), as a fishery may target small rather than large fish which could lead to a dominance of fast-growing animals in the fish population. 
- [x] The introduction mentions mixed-effect and hierarchical models, but leaves the reader to ponder why they were describe here (e.g. were they used in this study?). 
- [x] 2. Please present the model fits from all four growth models and combine them to one figure (not separately as in current Figures 1 and 3) so that the reader can easily compare the impact of the different model structures. 
My main points of concerns are about the simulation: 
- [x] 3. The logic and flow of this paper would be much helped if the evaluation of the method through simulation was reported before the actual application of the method.
- [x] 4. The description of the simulation is unclear and insufficient to exactly understand the logic of the simulations and how they were performed. Please describe in detail what the general approach was and what it tests? 
- [x] I could also not understand some details, such as in lines 240-243: do you mean that for each sample, you randomly selected two out of the three parameters age at release, age at recapture and time at liberty, then randomly select estimates for those two parameters and finally calculate the parameter value for the third parameter?
- [x] 5. I remain unconvinced that the simulation fully tests the proposed method in the intended way. As far as I understood, you may have tested some statistical properties of the growth model, but not whether the model does correctly and unambiguously describe the actual processes of growth. 	
By deriving samples from the real data set as it was done in this study, the underlying processes that have led to the structure of these real data remain unknown. To conduct an simulation evaluation correctly, you need to fully simulate all processes when creating simulation data. This must be done to avoid false-positive conclusions about growth processes, where e.g. the preferred model includes variation in k and z, but the data was only created with variation in k. I suggest you conduct four simulation scenarios where data are created with (1) nor variation, (2) with variation in k, (3) variation in z, and (4) variation in k and z. Each of these scenarios is then evaluated with all four model structures. The same approach could also be used if you want to further expand the evaluation and investigate e.g. the impact of annual/spatial variation in growth between animals as touched on in the Discussion. These simulations can be conditioned with toothfish-like parameters,
but of course proof of generality of the method would be beneficial. 
- [x] 6. What is the consequence of fixing <PSI> to values other than 0 (line 167)? Are the conclusions the same?

Minor comments: 
- [x] 7. Please provide all parameter values that you use for the simulation in a table, especially from non-publicly available working group papers such as Dunn et al. (2006). 
- [x] 8. Lines 137-138 is repeated in lines 146-149. Be more specific on what other time intervals you tested. 
- [x] 9. Avoid judgemental descriptions (e.g. 'reasonable' in line 216), and replace with e.g. 'to evaluate potential bias and precision of the models'. 
- [x] 10. I don't consider that papers in review should be cited in a publication, but leave this issue to the editor of this journal to decide. 
- [x] 11. There are also a number of grammatical and word errors in the text which should be easily picked up in the editorial process.

**Comment by quantifish** [comment]
OK so looking at point 5 above, the most substantial edit. I'm looking to get some input from you here Jim.

The reviewer states: "By deriving samples from the real data set as it was done in this study, the underlying processes that have led to the structure of these real data remain unknown." 

Presumably here they refer to the para in our paper starting line 239: "For each individual in each of the scenario/power simulations, sex was sampled with replacement from the observed sex of individuals in the toothfish data set.  The age at release, age at recapture and time at liberty were sampled independently from the observed individuals in the toothfish data set also, then one of the three variables was chosen at random and calculated using the other two variables and rounded to the nearest integer".

Well yes, the underlying processes that have led to the structure of these data is unknown and likely to be far more complex than simply simulating age at release, recapture and time at liberty independently, that is why we did this. We also suggest on line 250: "Sampling in this way ensured that the distribution of each of the variables approximated those observed the real-world data set, without the need for sampling from complex joint distributions (e.g., copulas)." I think we could explain this a little more in the text but don't think it is really worth changing. 

I am happy to simulate sex independently (i.e. from a binomial rather than sampling with replacement from data set). Not happy with simulating age at release, recapture and time at liberty independently.

What do you think Jim????

**Comment by quantifish** [comment]
Looking at point 5 above again. The reviewer also says "I suggest you conduct four simulation scenarios where data are created with (1) nor variation, (2) with variation in k, (3) variation in z, and (4) variation in k and z. Each of these scenarios is then evaluated with all four model structures." 

Well we did simulate exactly as stated above. The reviewer is suggesting we use ALL four estimation models on ALL four simulated data sets. 

Remembering also that we have done a power analysis with four different sample sizes for each of the four scenarios and 200 replicates. So we already have 4 x 4 x 200 different simulation/estimation experiments. Th reviewer is suggesting we do 4 x 4 x 200 x 4. Our simulation/estimation experiment took about 1 week to complete. So this will take about 1 month. 

What are your thoughts here Jim???

**Comment by James-Thorson** [comment]
Darcy,

A few quick thoughts:

* Its true that I prefer to simulate directly from a data generating
process that governs the sampling intensity as well as the stochastic and
deterministic terms.  So yes, I would probably have estimated the age at
first tagging and time at liberty as an exponentially distributed process,
estimating the mean from the data, and used this to simulate the data, and
similar for the sex (a bernoulli with mean drawn from the data).  E.g.,
here: http://icesjms.oxfordjournals.org/content/69/4/635.short.  But if you
want to retain the nonparametric bootstrap method, I think you could argue
it.

* I do think this reviewers suggestion has merit.  I basically think we
could only do the power analysis for one data-generating scenario (i.e.,
variation in K and z) and all estimation models, with 4 x 4 x 200 runs.  I
think its reasonable to do another 4 x 4 x 200 runs, with 4 estimation
models, 4 simulation scenarios, and 200 replicates each, with sample size
fixed at what we saw in the data.  Breaking up factorials is a standard
trick, e.g., here:
http://www.nrcresearchpress.com/doi/abs/10.1139/cjfas-2012-0330.  Anyway,
this would double simulation design size, but wouldn't require rerunning
the power analysis.

As for other tasks, I really don't have much time the next month, and would
prefer that you take the lead on these revisions where possible.

cheers,
jim

**Comment by quantifish** [comment]
OK, I'm gonna argue the bootstrap method so I dont need to redo the power analysis. If it turns out that I do need to change to sampling from distributions then by the time they get back to me it will be next month and I'll have time to work on this stuff.

Will do the 4 x 4 x 200 simulation as suggested by reviewer.

I'll make all changes then pass paper on to you with track changes/comments in the text.

**Comment by quantifish** [comment]
Hey again Jim.

Sorry about this Jim, I know you're busy, but it's been on my mind a little.

I'm gonna bring up the Age1, Age2, time at liberty thing again. So I've done that bootstrap thing that you don't really like. The alternative is to simulate Age1, Age2 and time at liberty from distributions (that are fitted to the data, you mention this above).

You may or may not remember that I looked into this a little bit. I dug up the plots that I created while looking in to this (I couldn't find the code though, it'll be somewhere). But the plots below shows the distributions of observed (in the true toothfish data) Age1, Age2 and time at liberty in black and what happens if we simulate from lognormal distributions for each independently:

![sim-age-liberty-2](https://cloud.githubusercontent.com/assets/5566375/7619812/454ecd40-fa0f-11e4-9797-8c9afef9f25f.png)

This next plot shows the distributions of observed (in the true toothfish data) Age1, Age2 and time at liberty in black again and what happens if I use my clunky bootsrap method:

![sim-age-liberty-1](https://cloud.githubusercontent.com/assets/5566375/7619793/2f40887c-fa0f-11e4-9836-be125c71cc51.png)

You can see that each method has its pros and cons, but the bottom right panel in each plot is what worries me the most.

So, am I overthinking this and should I just not worry about this and use the fitted distributions? Just keen to get your opinion on this once more.

**Comment by James-Thorson** [comment]
Personally, I would still use a proposed data-generating process, rather
than the bootstrap.  I see your point that time-at-liberty has a more
peaked distribution that an exponential (and maybe also some seasonal
sinuosity).  But that just affects how much contrast we get in estimating
growth increments.  The main reason I'd use an explicit DGP is because hte
reviewer asked, and I don't like rolling dice during hte review process.
It also seems like one of the easier requests, given that machine time is
cheaper than human (editing) time.

but as I said, if you want to argue against it in the response, I have no
objection.

jim

**Comment by quantifish** [comment]
Point taken, I will change to a proper distribution to sample these. I've used lognormal's above, you mentioned an exponential though. Any preference here?

**Comment by quantifish** [comment]
I went with lognormal for age1 and exponential for liberty.

**Comment by James-Thorson** [comment]
Makes sense.

**Comment by quantifish** [comment]
Any issues that you know of at the moment with the current version of TMB? I am fitting our model to simulated data and sometimes it works, sometimes getting the error msg:

TMB has received an error from Eigen. The following condition was not met:
index >= 0 && index < size()
Please check your matrix-vector bounds etc., or run your program through a debugger.

Process R aborted (core dumped) at Fri May 15 07:35:02 2015

**Comment by quantifish** [comment]
P.S. ran it through the TMB debugger and it didn't give any errors...

**Comment by James-Thorson** [comment]
Hmm, that's a new one to me.  They have been adding additional automated
debugging features.  I'd make sure that the index for z isn't overrunning
the random effect vector for that component, and then post it to the TMB
group, with an R dump for a replicate where it fails.  you could also use a
previous numbered release and avoid the issue.

jim

**Comment by quantifish** [comment]
OK found a line to do with y_devs that the model didnt like. As we are not using these anyway I just commented it out, dont have time to fix it now.

So this is running now, I'd expect this to take over a week. I'll tidy text in the meantime, do plots once sim is done.

**Comment by quantifish** [comment]
Just to keep you updated - about 30% of the simulation fits are done now. Getting there. I've done a lot of the text updates too, will have all the text done by the time the simulations are done.
